version: "3.8"
services:
  postgres:
    image: postgres:15-alpine
    env_file:
      - .env
    restart: on-failure:5
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env
    restart: on-failure:5
    working_dir: /go/src/app
    links:
      - "postgres:postgres"
    volumes:
      - .:/go/src/app
    ports:
      - "8443:8443"
      - "8080:8080"

volumes:
  postgres-data:
